In [1]:
#var6 task 1
import numpy as np

# Задаем размерность матрицы
n = 5  # Например, 5x5 матрица

# Генерируем случайную целочисленную квадратную матрицу
matrix = np.random.randint(1, 101, size=(n, n))  # Значения от 1 до 100

# Находим наибольший элемент в каждой строке
max_in_rows = np.max(matrix, axis=1)

# Находим наименьший элемент в каждом столбце
min_in_columns = np.min(matrix, axis=0)

# Вывод результатов
print("Случайная матрица:")
print(matrix)
print("Наибольшие элементы в каждой строке:", max_in_rows)
print("Наименьшие элементы в каждом столбце:", min_in_columns)

Случайная матрица:
[[32 12 31 40 56]
 [11 28 84 79 83]
 [31 21 12 54 65]
 [ 5 17 44 98 86]
 [63 88 95 82 58]]
Наибольшие элементы в каждой строке: [56 84 65 98 95]
Наименьшие элементы в каждом столбце: [ 5 12 12 40 56]


In [9]:
#var6 task 2
import numpy as np

# Задаем размерность матрицы (нечетное N)
N = 5  # Например, 5x5 матрица

# Генерируем случайную целочисленную квадратную матрицу с различными элементами
matrix = np.random.choice(range(1, 101), size=(N, N), replace=False)
print('Матрица до изменения:')
print(matrix)
# Находим элементы главной и побочной диагоналей
main_diagonal = [matrix[i][i] for i in range(N)]
secondary_diagonal = [matrix[i][N - i - 1] for i in range(N)]

# Объединяем оба списка диагональных элементов
diagonal_elements = main_diagonal + secondary_diagonal

# Находим наибольший элемент и его индекс
max_element = max(diagonal_elements)
max_index = diagonal_elements.index(max_element)

# Находим позицию на матрице и пересечения диагоналей
if max_index < N:
    max_position = (max_index, max_index)  # Главная диагональ
else:
    max_position = (max_index - N, N - (max_index - N) - 1)  # Побочная диагональ

# Элемент на пересечении диагоналей
center_index = N // 2
center_element = matrix[center_index][center_index]

# Меняем местами
matrix[max_position] = center_element
matrix[center_index][center_index] = max_element

# Выводим результаты
print("Матрица после изменения:")
print(matrix)
print("Наибольший элемент:", max_element)

Матрица до изменения:
[[34 26 59 10 58]
 [11 76 86 19 41]
 [47 56 67 94 12]
 [99 98 93 22 15]
 [81 40 33  1  3]]
Матрица после изменения:
[[34 26 59 10 58]
 [11 76 86 19 41]
 [47 56 98 94 12]
 [99 67 93 22 15]
 [81 40 33  1  3]]
Наибольший элемент: 98
